[versions]
agp = "8.11.2"
androidxJunit = "1.1.5"
biometric = "1.1.0"
blurview = "version-2.0.3"
coreSplashscreen = "1.0.1"
coreTesting = "2.2.0"
currencyedittext = "1.0.0"
datastorePreferences = "1.1.7"
dotsindicator = "5.1.0"
firebaseBom = "34.3.0"
firebaseConfig = "23.0.1"
firebaseMessaging = "25.0.1"
glide = "4.16.0"
gson = "2.13.2"
hiltAndroid = "2.57.2"
hiltAndroidCompiler = "2.57.2"
jacksonDatabind = "2.20.0"
jacksonModuleKotlin = "2.20.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
kotlinxCoroutinesPlayServices = "1.10.2"
kotlinxCoroutinesTest = "1.10.2"
kotlinxCoroutinesTestVersion = "1.7.3"
lifecycleLivedata = "2.9.4"
lifecycleViewmodel = "2.9.4"
lottie = "6.6.9"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
firebaseFunctions = "22.0.1"
mockk = "1.14.6"
mpandroidchart = "v3.1.0"
navigationFragmentKtx = "2.9.5"
navigationUiKtx = "2.9.5"
pinview = "1.4.4"
prettytime = "5.0.1.Final"
shimmer = "0.5.0"
tinkAndroid = "1.18.0"
navigationFragment = "2.9.5"
navigationUi = "2.9.5"
turbine = "1.2.1"
viewpagerindicator = "1.2.3"
uiDesktop = "1.7.0"

[libraries]
biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
blurview = { module = "com.github.Dimezis:BlurView", version.ref = "blurview" }
core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
currencyedittext = { module = "com.cottacush:CurrencyEditText", version.ref = "currencyedittext" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
firebase-config = { module = "com.google.firebase:firebase-config", version.ref = "firebaseConfig" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
dotsindicator = { module = "com.tbuonomo:dotsindicator", version.ref = "dotsindicator" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
firebase-storage = { module = "com.google.firebase:firebase-storage" }
google-firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompiler" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jacksonDatabind" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jacksonModuleKotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit-v115 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutinesPlayServices" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
kotlinx-coroutines-test-v173 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTestVersion" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "lifecycleLivedata" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycleViewmodel" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-functions = { group = "com.google.firebase", name = "firebase-functions", version.ref = "firebaseFunctions" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
pinview = { module = "io.github.chaosleung:pinview", version.ref = "pinview" }
prettytime = { module = "org.ocpsoft.prettytime:prettytime", version.ref = "prettytime" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
tink-android = { module = "com.google.crypto.tink:tink-android", version.ref = "tinkAndroid" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
viewpagerindicator = { module = "com.github.zhpanvip:viewpagerindicator", version.ref = "viewpagerindicator" }
ui-desktop = { group = "androidx.compose.ui", name = "ui-desktop", version.ref = "uiDesktop" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

