[versions]
agp = "8.11.2"
coreSplashscreen = "1.0.1"
datastorePreferences = "1.1.7"
dotsindicator = "5.1.0"
firebaseBom = "34.2.0"
firebaseConfig = "23.0.0"
glide = "4.16.0"
gson = "2.13.1"
hiltAndroid = "2.57.1"
hiltAndroidCompiler = "2.57.1"
jacksonDatabind = "2.20.0"
jacksonModuleKotlin = "2.20.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
lifecycleLivedata = "2.9.3"
lifecycleViewmodel = "2.9.3"
lottie = "6.6.7"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
firebaseFunctions = "22.0.0"
navigationFragmentKtx = "2.9.4"
navigationUiKtx = "2.9.4"
shimmer = "0.5.0"
tinkAndroid = "1.18.0"
navigationFragment = "2.9.4"
navigationUi = "2.9.4"

[libraries]
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
firebase-config = { module = "com.google.firebase:firebase-config", version.ref = "firebaseConfig" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
dotsindicator = { module = "com.tbuonomo:dotsindicator", version.ref = "dotsindicator" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
firebase-storage = { module = "com.google.firebase:firebase-storage" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompiler" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jacksonDatabind" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jacksonModuleKotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "lifecycleLivedata" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycleViewmodel" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-functions = { group = "com.google.firebase", name = "firebase-functions", version.ref = "firebaseFunctions" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
tink-android = { module = "com.google.crypto.tink:tink-android", version.ref = "tinkAndroid" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

